### ISSUE TITLE
how to download coupon in iOS through API

### ISSUE THREAD

**Issue by kukkadapukarhtik** [passworks/passworks-api#4]
i go through the passworks .create campaign and published it but i want to download coupon into my mobile wallet using API in iOS

**Comment by lmmendes** [comment]
Using the Passworks API after calling "create pass" endpoint (ex: using the coupon endpoint see here for more details  https://github.com/passworks/passworks-api/blob/master/v2/sections/coupon.md#creating-a-paw-planet-coupon-pass )

You will get a JSON response with similar content:

```
{
   ...., // removed other attributes
  "page_url": "http://get.passworks.io/I5dPyf_j2Q/-zGkMq8orhAE1x9l08yLCQ",
  "pkpass_url": "http://get.passworks.io/I5dPyf_j2Q/-zGkMq8orhAE1x9l08yLCQ.pkpass"
}
```

The important key from the JSON response is `pkpass_url` this contains the URL for the Pass.

Then using iOS PassKit framework from Apple follow these instructions:

Before attempting to add passes to Wallet, see whether the device supports adding passes. Call the `PKAddPassesViewController` class's `canAddPasses` method. If this method returns **YES**, add your passes.

To add a single pass, download the signed, encrypted package, and instantiate a PKPass object using the downloaded data. Next, create a `PKAddPassesViewController` instance for the pass object. Present this view controller to the user.

This view controller shows the user your pass. The user can then approve or reject the pass.

For more information please visit  https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/PassKit_PG/DistributingPasses.html#//apple_ref/doc/uid/TP40012195-CH11-SW2
